name: First workflow #A name for the WF. Always the first like

# When the WF to run
on: workflow_dispatch # This means we can start the WF manually.

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Gaurav Misra"
      - name: Print good bye
        run: echo "Done... bye!"
