name: Run test for a react app

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 02StartingProject
    steps:
      - name: Get latest code from repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: 02StartingProject/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get latest code from repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: 02StartingProject/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./02StartingProject/build
          run: "echo 'Deploying to GitHub Pages...'"
